import Head from "next/head";
import Link from "next/link";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>Home page</h3>
      <ul>
        <li>
          <Link href="/routes">routes</Link>
        </li>
        <li>
          <Link href="/pre-rendering">pre-rendering</Link>
        </li>
      </ul>
    </div>
  );
}
